import React from 'react';
import { DocumentData } from '../types';

interface DocumentSidebarProps {
  activeDocIds: string[];
  documents: DocumentData[]; // Now receives data from parent
}

const DocumentSidebar: React.FC<DocumentSidebarProps> = ({ activeDocIds, documents }) => {
  const personalDocs = documents.filter(d => d.category === 'personal');
  const medicalDocs = documents.filter(d => d.category === 'medical');
  const schemeDocs = documents.filter(d => d.category === 'schemes');
  
  // PDF Generator Function
  const handleDownload = (doc: any) => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>${doc.filename}</title>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
            .header { border-bottom: 2px solid #0d9488; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
            .logo { font-size: 28px; font-weight: bold; color: #0d9488; }
            .subtitle { color: #666; font-size: 14px; }
            .doc-title { font-size: 24px; margin-bottom: 20px; color: #1f2937; }
            .content { white-space: pre-wrap; line-height: 1.6; background: #f9f9f9; padding: 30px; border-radius: 8px; border: 1px solid #e5e7eb; font-size: 14px; }
            .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }
            .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); opacity: 0.05; font-size: 100px; font-weight: bold; color: #000; z-index: -1; pointer-events: none; }
          </style>
        </head>
        <body>
          <div class="watermark">SEHAT SAATHI</div>
          <div class="header">
            <div class="logo">Sehat Saathi</div>
            <div class="subtitle">Official Health Record • ${new Date().toLocaleDateString()}</div>
          </div>
          <h1 class="doc-title">${doc.title}</h1>
          <div class="content">${doc.content}</div>
          <div class="footer">
            Generated by Sehat Saathi AI • Verified by ASHA Network<br>
            For medical use only.
          </div>
        </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  const renderDocSection = (title: string, docs: typeof documents, colorClass: string, dotColor: string) => (
    <div>
        <h3 className={`text-xs font-semibold ${colorClass} uppercase tracking-wider mb-3 flex items-center`}>
        <span className={`w-2 h-2 rounded-full ${dotColor} mr-2`}></span>
        {title}
        </h3>
        <ul className="space-y-2">
        {docs.map((doc) => (
            <li 
            key={doc.id}
            className={`group flex items-center p-2 rounded-lg text-sm border transition-all duration-300 ${
                activeDocIds.includes(doc.id) 
                ? `bg-slate-50 border-slate-200 shadow-sm ring-1 ring-slate-300` 
                : 'bg-white border-slate-100 text-slate-600 hover:bg-slate-50'
            }`}
            >
            <span className="text-lg mr-3">{doc.icon}</span>
            <div className="flex-1 min-w-0">
                <p className="font-medium truncate">{doc.filename}</p>
                <p className="text-xs text-slate-400 truncate">{doc.title}</p>
            </div>
            {/* Download Button */}
            <button 
                onClick={(e) => { e.stopPropagation(); handleDownload(doc); }}
                className="opacity-0 group-hover:opacity-100 p-2 text-slate-400 hover:text-teal-600 transition hover:bg-slate-100 rounded-full"
                title="Download PDF"
            >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
            </button>
            {activeDocIds.includes(doc.id) && (
                <span className={`w-2 h-2 rounded-full ${dotColor} animate-pulse ml-2`}></span>
            )}
            </li>
        ))}
        </ul>
    </div>
  );

  return (
    <div className="w-full md:w-80 flex-shrink-0 bg-white border-r border-slate-200 h-full overflow-y-auto flex flex-col">
      <div className="p-4 border-b border-slate-100 bg-slate-50">
        <h2 className="text-lg font-bold text-slate-800">My Records</h2>
      </div>

      <div className="p-4 space-y-6">
        {renderDocSection("Rani Devi's Files", personalDocs, "text-rose-500", "bg-rose-500")}
        {renderDocSection("Government Schemes", schemeDocs, "text-purple-600", "bg-purple-600")}
        {renderDocSection("Medical Guides", medicalDocs, "text-teal-600", "bg-teal-600")}
      </div>
    </div>
  );
};

export default DocumentSidebar;